import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { themeSections } from '../theme/theme-source.mjs';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const webRoot = join(scriptDir, '..');

function renderTokensCss() {
  const lines = [
    '/* Generated by npm run sync:theme. Edit apps/web/theme/theme-source.mjs instead. */',
    ':root {',
    '  color-scheme: dark;',
    '',
  ];

  for (const section of themeSections) {
    lines.push(`  /* ${section.title} */`);

    for (const [tokenName, tokenValue] of Object.entries(section.tokens)) {
      lines.push(`  ${tokenName}: ${tokenValue};`);
    }

    lines.push('');
  }

  lines.push('}');

  return `${lines.join('\n')}\n`;
}

async function syncTheme() {
  const tokensPath = join(webRoot, 'src', 'styles', 'tokens.css');

  await mkdir(dirname(tokensPath), { recursive: true });
  await writeFile(tokensPath, renderTokensCss(), 'utf8');
}

await syncTheme();
