import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { getThemeToken, themeSections } from '../theme/theme-source.mjs';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const webRoot = join(scriptDir, '..');

function renderTokensCss() {
  const lines = [
    '/* Generated by npm run sync:theme. Edit apps/web/theme/theme-source.mjs instead. */',
    ':root {',
    '  color-scheme: dark;',
    '',
  ];

  for (const section of themeSections) {
    lines.push(`  /* ${section.title} */`);

    for (const [tokenName, tokenValue] of Object.entries(section.tokens)) {
      lines.push(`  ${tokenName}: ${tokenValue};`);
    }

    lines.push('');
  }

  lines.push('}');

  return `${lines.join('\n')}\n`;
}

function renderFaviconSvg() {
  const brandMark = getThemeToken('--color-brand-mark');
  const background = getThemeToken('--color-background');
  const warning = getThemeToken('--color-warning');

  return [
    '<!-- Generated by npm run sync:theme. Edit apps/web/theme/theme-source.mjs instead. -->',
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">',
    `  <ellipse cx="32" cy="50" rx="21" ry="6.5" fill="${brandMark}" />`,
    `  <path d="M17 48 31 8 49 48Z" fill="${brandMark}" />`,
    `  <path d="M17.5 48c4.6-1.9 9.4-2.8 14.5-2.8 6.6 0 12.2 1 16.7 2.8" fill="none" stroke="${background}" stroke-linecap="round" stroke-width="2" />`,
    `  <path d="m31 18 2 5.4h5.7l-4.6 3.4 1.8 5.4-4.9-3.3-4.8 3.3 1.7-5.4-4.5-3.4h5.6Z" fill="${warning}" />`,
    `  <path d="m22 29 1.4 3.8h4l-3.2 2.4 1.2 3.9-3.4-2.3-3.3 2.3 1.2-3.9-3.2-2.4h4Z" fill="${warning}" />`,
    `  <path d="m38 33 1.5 4.1h4.4l-3.5 2.6 1.3 4.1-3.7-2.5-3.6 2.5 1.3-4.1-3.5-2.6h4.4Z" fill="${warning}" />`,
    '</svg>',
    '',
  ].join('\n');
}

async function syncTheme() {
  const tokensPath = join(webRoot, 'src', 'styles', 'tokens.css');
  const faviconPath = join(webRoot, 'public', 'favicon.svg');

  await mkdir(dirname(tokensPath), { recursive: true });
  await mkdir(dirname(faviconPath), { recursive: true });

  await Promise.all([
    writeFile(tokensPath, renderTokensCss(), 'utf8'),
    writeFile(faviconPath, renderFaviconSvg(), 'utf8'),
  ]);

  console.log('Synced tokens.css and favicon.svg from theme-source.mjs');
}

await syncTheme();